### ISSUE TITLE
Settings File not found

### ISSUE THREAD

**Issue by muneeb-mashhood** [Bobisback/BobisbackCombinedMods#1]
I have downloaded your Mod from [this](http://www.timberandstonegame.com/forum/viewtopic.php?f=22&t=6627) forum. Copied it to the saves folder. When I run the game it shows black screen and a log named BobisbackLog.txt is created in saves folder, which has only this line

Settings Failed To Load:  Could not find file "E:\Games\Timber and Stone\saves\BobisbackCombinedModsSettings.txt".

Where can i find that settings file?

**Comment by Bobisback** [comment]
Ya that is a warning not really a error. If I cannot find the file I create
a new one with default settings. If I am never getting to the point of
creating one with default settings then it is crashing before it creates
the file. My first thing is make sure you have the 1.7.1 of T&S. Any other
version will cause a simular issue to what you are experiencing.

If this is not the problem then let me know some details about your
envirment.

OS, OS version(aka win 10/osx 10.6), Steam or not?, What version of my mod.

Like I said the most likely cause of the issues is wrong game version.
Start the game without my mod and make sure that 1.7.1 is in the bottom
left of the screen.

See ya,
Bob

**Comment by muneeb-mashhood** [comment]
Thanks for pointing out the version. I thought I was running 1.7.1 but apparently it was 1.7. Upgrading to 1.7.1 did it.

Thanks Bob for this mod.
